# Generated by Django 5.0.2 on 2024-03-05 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_category_order_order_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='catID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.category'),
        ),
    ]
